import turtle
t = turtle.Pen()
t.speed(0)
def atleta0(kratka):
    t.forward(kratka)
    t.left(90)
    t.forward(kratka * 2)
    t.right(90)
    for i in range(4):
        t.forward(kratka * 2)
        t.left(90)
    t.forward(kratka * 2)
    t.right(90)
    t.forward(kratka * 2)
    t.left(90)
    t.forward(kratka)
    t.setheading(180)
    t.forward(kratka)
    t.right(90)
    t.forward(kratka * 4)
    t.left(90)
    t.forward(kratka / 2)
    for i in range(4):
        t.forward(kratka)
        t.right(90)
    t.forward(kratka)
    t.forward(kratka / 2)
    t.forward(kratka)
    t.left(90)
    t.forward(kratka * 2)
    t.up()
    t.forward(kratka / 2)
    t.down()
    t.right(90)
    t.forward(kratka)
    t.right(90)
    t.forward(kratka / 2)
    t.backward(kratka)
    t.forward(kratka / 2)
    t.left(90)
    t.forward(kratka / 2)
    t.right(90)
    t.forward(kratka)
    t.backward(kratka * 2)
    t.forward(kratka)
    t.left(90)
    t.forward(kratka / 2)
    t.right(90)
    t.forward(kratka / 2)
    t.forward(kratka)
    t.backward(kratka * 3)
    t.forward(kratka)
    t.forward(kratka / 2)
    t.right(90)
    t.forward(kratka * 7)
def atleta1(kratka):
    t.forward(kratka)
    t.left(90)
    t.forward(kratka * 2)
    t.right(90)
    for i in range(4):
        t.forward(kratka * 2)
        t.left(90)
    t.forward(kratka * 2)
    t.right(90)
    t.forward(kratka * 2)
    t.left(90)
    t.forward(kratka)
    t.setheading(180)
    t.forward(kratka)
    t.right(90)
    t.forward(kratka * 4)
    t.left(90)
    t.forward(kratka / 2)
    for i in range(4):
        t.forward(kratka)
        t.right(90)
atleta0(50)
    
