import turtle
t = turtle.Pen()
t.speed(0)

def zielona_linia():
    t.color("black", "green")
    t.begin_fill()
    t.left(45)
    t.forward(10)
    t.right(45)
    t.forward(20)
    t.right(45)
    t.forward(10)
    t.right(90)
    t.forward(10)
    t.right(45)
    t.forward(20)
    t.right(45)
    t.forward(10)
    t.end_fill()
    t.setheading(270)
    t.up()
    t.forward(34.14)
    t.down()

def zulta_linia():
    t.color("black", "yellow")
    t.begin_fill()
    t.left(45)
    t.forward(10)
    t.right(45)
    t.forward(20)
    t.right(45)
    t.forward(10)
    t.right(90)
    t.forward(10)
    t.right(45)
    t.forward(20)
    t.right(45)
    t.forward(10)
    t.end_fill()
    t.setheading(0)
    t.up()
    t.forward(34.14)
    t.down()

def mozaika(ilosc):
    t.up()
    t.setx(-1 * 34.14 * ilosc * 0.5 )
    t.sety(-1 * 34.14 * ilosc * 0.5)
    t.down()
    for x in range(ilosc + 1):
        for i in range(ilosc):
            zulta_linia()
        t.up()
        t.left(90)
        t.forward(34.14)
        t.left(90)
        t.forward(34.14 * ilosc)
        t.setheading(0)
        t.down()
    t.up()
    t.right(90)
    t.forward(34.14)
    t.down()
    for z in range(ilosc + 1):
        for o in range(ilosc):           
            zielona_linia()
        t.setheading(0)
        t.up()
        t.forward(34.14)
        t.left(90)
        t.forward(34.14 * ilosc)
        t.setheading(270)
        t.down()
       
mozaika(5)

