spacje = ' ' * 25
print('%s Pod Krzyzem12' % spacje)
print('%s Wiatrolomy Dolne' % spacje)
print('%s Chrapstwo Zachod' % spacje)
print()
print()
print('Szanowny Panie, ')
print()
print('pragne poinformowac, ze z dachu oslaniajocego szalet')
print('wczorajszej nocy ubylo kilka dachowek')
print('Podejrzewam, ze przyczyno byly wzmozone wiatry gnebioce mieszkancow naszej osady.')
print()
print('Z wyrazami szacunku')
print('Maciej Fasola')
