import turtle
t = turtle.Pen()
t.speed(0)
t.left(90)
kratka = 26
def wiatrak():
    t.forward(kratka * 3)
    t.color("black", "orange")
    t.begin_fill()
    t.right(90)
    t.forward(kratka * 2)
    t.left(135)
    t.forward(36.77)
    t.left(45)
    t.forward(kratka)
    t.left(90)
    t.forward(kratka)
    t.setheading(0)
    t.end_fill()
    t.color("black", "green")
    t.up()
    t.left(90)
    t.forward(kratka)
    t.right(90)
    t.forward(kratka)
    t.left(90)
    t.down()
    t.begin_fill()
    t.forward(kratka * 2)
    t.left(135)
    t.forward(36.77)
    t.left(45)
    t.forward(kratka)
    t.left(90)
    t.forward(kratka)
    t.setheading(0)
    t.end_fill()
    t.up()
    t.setheading(180)
    t.forward(kratka)
    t.color("black", "orange")
    t.down()
    t.begin_fill()
    t.forward(kratka)
    t.right(45)
    t.forward(36.77)
    t.right(135)
    t.forward(kratka * 2)
    t.end_fill()
    t.color("black", "green")
    t.up()
    t.right(90)
    t.forward(kratka)
    t.down()
    t.begin_fill()
    t.forward(kratka)
    t.right(45)
    t.forward(36.77)
    t.right(135)
    t.forward(kratka * 2)
    t.right(90)
    t.forward(kratka)
    t.end_fill()
    
def duzy_wiatrak():
    wiatrak()
    t.right(90)
    t.forward(kratka * 4)
    t.left(90)
    t.forward(kratka * 2)
    t.left(90)
    t.forward(kratka * 5)
    wiatrak()
    t.right(90)
    t.forward(kratka * 9)
    t.left(90)
    t.forward(kratka * 2)
    t.left(90)
    
def wiatraki(ilosc):
    if ilosc == 1:
        duzy_wiatrak()
        wiatrak()
    else:
        for i in range(ilosc):
            duzy_wiatrak()
        wiatrak()
wiatraki(6)
